---

apiVersion: v1
kind: Pod
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: prep-node-data-vol
  name: prep
spec:
  containers:
    - image: iconloop/prep-node
      name: prep-node
      env:
        - name: CERT_PATH
          value: /cert
        - name: FASTEST_START
          value: "yes"
        - name: ICON_LOG_LEVEL
          value: DEBUG
        - name: LOOPCHAIN_LOG_LEVEL
          value: DEBUG
        - name: NETWORK_ENV
          value: mainnet
{{/*#        - name: ENDPOINT_URL*/}}
{{/*#        - name: PRIVATE_KEY_FILENAME*/}}
{{/*#        - name: PRIVATE_PASSWORD*/}}
      ports:
        - containerPort: 9000
{{/*        - containerPort: 7100*/}}
      resources: {}
      securityContext:
        capabilities:
          add:
            - SYS_TIME
      volumeMounts:
        - mountPath: /data
          name: prep-node-data-vol
        - mountPath: /cert
          name: prep-node-cert-vol
  restartPolicy: OnFailure
  volumes:
    - name: prep-node-data-vol
      persistentVolumeClaim:
        claimName: prep-node-data-vol
    - name: prep-node-cert-vol
      persistentVolumeClaim:
        claimName: prep-node-cert-vol
status: {}

