---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: prep-node-data-vol
  name: prep-node-data-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 360Gb
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: prep-node-data-vol
  name: prep-node-cert-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}