{{ if not .Values.generateCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prep-node.certificate-password" .}}
type: Opaque
data:
  password: {{ .Values.certificatePassword | b64enc }}
{{ end }}