{{ if not .Values.generateCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prep-node.certificate-name" .}}
type: Opaque
data:
  cert.pem: {{ .Values.certificateContents | b64enc }}
{{ end }}