apiVersion: v1
kind: Service
metadata:
  name: {{ include "prep-node.rpcService" . }}
  labels:
    node: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.rpcPort }}
      name: json-rpc
  selector:
    node: {{ .Release.Name }}
    app: {{ .Release.Name }}
  type: LoadBalancer